# Generated by Django 4.2 on 2023-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_exam_topic_exam_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.CharField(choices=[('answer_a', 'A javob'), ('answer_b', 'B javob'), ('answer_c', 'C javob'), ('answer_d', 'D javob')], default='answer_a', max_length=10, verbose_name='Javob'),
        ),
    ]
